INSERT INTO channels (d_code, name, commission_rate, enabled) VALUES
('default', '默认渠道', 0.1000, TRUE),
('demo', '演示渠道', 0.1500, TRUE);

INSERT INTO products (id, label, icon, badge, banner, process_variant, form_variant, task_type, flow_type,
    title_field_label, title_placeholder, pro_link_text, submit_label, agreement_text, show_faq, center_title, sort_order) VALUES
('graduation', '毕业论文', '🎓', NULL, '你只负责输入标题，写论文的这100小时，小微来帮你节省', 'standard', 'graduation', 'paper_generate', 'both',
 '提交论文标题', '输入5-50字论文标题，如果不知道写什么标题，可以试试推荐哦~', '切换至专业版，设字数、选提纲', '立即生成',
 '我已阅读并同意：生成的论文范文仅用于参考，不作为毕业、发表等用途', TRUE, FALSE, 1),
('journal', '期刊论文', '📰', NULL, NULL, 'journal', 'journal', 'paper_generate', 'both',
 '提交论文标题', '输入5-50字论文标题，如果不知道写什么标题，可以试试推荐哦~', '切换至专业版，可选提纲摘要', '立即生成',
 '我已阅读并同意：生成的论文范文仅用于参考，不作为毕业、发表等用途', TRUE, FALSE, 2),
('revise', 'AI无限改稿', '✨', NULL, NULL, 'revise', 'revise', 'revise', 'quick',
 '请上传文档', '', NULL, '立即改稿', '我已阅读并同意：改稿结果仅用于参考，请自行核对学术规范', TRUE, TRUE, 3),
('review', '文献综述', '📚', NULL, NULL, 'review', 'review', 'paper_generate', 'both',
 '提交文献综述标题', '输入5-50字论文标题，如果不知道写什么标题，可以试试推荐哦~', '切换至专业版，定制更多参数', '立即生成',
 '我已阅读并同意：生成的范文仅用于参考，不作为毕业、发表使用', TRUE, FALSE, 4),
('aigc', 'AIGC查重', '🔍', NULL, NULL, 'aigc', 'aigc', 'aigc_check', 'quick',
 '上传查重文件', '', NULL, '立即查重', NULL, TRUE, TRUE, 5),
('proposal', '开题报告', '📝', NULL, NULL, 'proposal', 'proposal', 'paper_generate', 'both',
 '提交开题报告标题', '输入5-50字论文标题，如果不知道写什么标题，可以试试推荐哦~', '切换至专业版，定制更多参数', '立即生成',
 '我已阅读并同意：生成的范文仅用于参考，不作为毕业、发表使用', TRUE, FALSE, 6),
('course', '课程论文', '📖', NULL, NULL, 'course', 'course', 'paper_generate', 'quick',
 '提交论文标题', '输入5-50字论文标题，如果不知道写什么标题，可以试试推荐哦~', NULL, '立即生成',
 '我已阅读并同意：生成的论文范文仅用于参考，不作为毕业、发表等用途', TRUE, FALSE, 7),
('task', '任务书', '📋', NULL, NULL, 'task', 'task', 'paper_generate', 'quick',
 '提交任务书标题', '输入完整的任务书标题，可获得更好的生成效果（5-50字或20词以内）', NULL, '立即生成',
 '我已阅读并同意：生成的范文仅用于参考，不作为毕业、发表使用', TRUE, FALSE, 8),
('paraphrase', '论文降重', '↓', '热', NULL, 'paraphrase', 'paraphrase', 'paraphrase', 'quick',
 '上传文件', '', NULL, '立即降重', '我已阅读并同意：生成的范文仅用于参考，不作为毕业、发表使用', TRUE, TRUE, 9),
('aigc-reduce', 'AIGC降重', '🤖', NULL, NULL, 'paraphrase', 'paraphrase', 'paraphrase', 'quick',
 '上传文件', '', NULL, '立即降重', '我已阅读并同意：降重结果仅用于参考，请自行核对', FALSE, TRUE, 10),
('ppt', '答辩PPT', '📊', NULL, NULL, 'ppt', 'ppt', 'ppt_generate', 'quick',
 '提交答辩主题', '输入答辩PPT主题或论文标题', NULL, '立即生成PPT',
 '我已阅读并同意：生成的论文范文仅用于参考，不作为毕业、发表等用途', TRUE, FALSE, 11),
('imitate', '论文仿写', '✍️', NULL, NULL, 'standard', 'generic', 'paper_generate', 'quick',
 '提交仿写标题', '输入需要仿写的论文标题或主题', NULL, '立即生成',
 '我已阅读并同意：生成的论文范文仅用于参考，不作为毕业、发表等用途', TRUE, FALSE, 12),
('ppt-master', 'PPT高定大师', '🎨', NULL, NULL, 'ppt', 'ppt', 'ppt_generate', 'quick',
 '提交PPT主题', '输入PPT主题与风格要求', NULL, '立即定制',
 '我已阅读并同意：生成的论文范文仅用于参考，不作为毕业、发表等用途', TRUE, FALSE, 13),
('lit-ppt', '文献汇报PPT', '📑', NULL, NULL, 'ppt', 'ppt', 'ppt_generate', 'quick',
 '提交汇报主题', '输入文献汇报主题', NULL, '立即生成',
 '我已阅读并同意：生成的论文范文仅用于参考，不作为毕业、发表等用途', TRUE, FALSE, 14),
('sci-en', 'SCI论文 英文', '🌐', NULL, NULL, 'journal', 'generic', 'paper_generate', 'wizard',
 '提交论文标题', 'Enter paper title (English)', NULL, 'Generate Now',
 '我已阅读并同意：生成的论文范文仅用于参考，不作为毕业、发表等用途', TRUE, FALSE, 15),
('sci-premium', 'SCI论文 高端', '💎', NULL, NULL, 'journal', 'generic', 'paper_generate', 'wizard',
 '提交论文标题', '输入SCI论文标题（英文）', NULL, '立即生成',
 '我已阅读并同意：生成的论文范文仅用于参考，不作为毕业、发表等用途', TRUE, FALSE, 16),
('report', '调研报告', '📈', NULL, NULL, 'standard', 'generic', 'paper_generate', 'quick',
 '提交调研主题', '输入调研报告主题', NULL, '立即生成',
 '我已阅读并同意：生成的论文范文仅用于参考，不作为毕业、发表等用途', TRUE, FALSE, 17),
('translate', '文献翻译', '🔤', NULL, NULL, 'upload', 'upload', 'file_translate', 'quick',
 '上传文献', '', NULL, '立即翻译', NULL, FALSE, TRUE, 18),
('intern', '实习报告', '💼', NULL, NULL, 'course', 'generic', 'paper_generate', 'quick',
 '提交实习报告标题', '输入实习报告标题', NULL, '立即生成',
 '我已阅读并同意：生成的论文范文仅用于参考，不作为毕业、发表等用途', TRUE, FALSE, 19),
('data', '数据分析', '📉', NULL, NULL, 'upload', 'upload', 'data_analysis', 'quick',
 '上传数据文件', '', NULL, '开始分析', NULL, FALSE, TRUE, 20),
('survey', '调查报告', '📋', NULL, NULL, 'standard', 'generic', 'paper_generate', 'quick',
 '提交调查主题', '输入调查报告主题', NULL, '立即生成',
 '我已阅读并同意：生成的论文范文仅用于参考，不作为毕业、发表等用途', TRUE, FALSE, 21),
('questionnaire', '问卷设计', '❓', NULL, NULL, 'standard', 'generic', 'paper_generate', 'quick',
 '提交问卷主题', '输入问卷研究主题', NULL, '立即生成',
 '我已阅读并同意：生成的论文范文仅用于参考，不作为毕业、发表等用途', TRUE, FALSE, 22),
('experiment', '实验报告', '🧪', NULL, NULL, 'course', 'generic', 'paper_generate', 'quick',
 '提交实验报告标题', '输入实验报告标题', NULL, '立即生成',
 '我已阅读并同意：生成的论文范文仅用于参考，不作为毕业、发表等用途', TRUE, FALSE, 23),
('book', '读后感', '📕', NULL, NULL, 'standard', 'generic', 'paper_generate', 'quick',
 '提交书名/主题', '输入书籍名称或读后感主题', NULL, '立即生成',
 '我已阅读并同意：生成的论文范文仅用于参考，不作为毕业、发表等用途', TRUE, FALSE, 24),
('ideology', '思想汇报', '⭐', NULL, NULL, 'standard', 'generic', 'paper_generate', 'quick',
 '提交汇报主题', '输入思想汇报主题', NULL, '立即生成',
 '我已阅读并同意：生成的论文范文仅用于参考，不作为毕业、发表等用途', TRUE, FALSE, 25);

INSERT INTO product_prices (product_id, degree, word_count, model_type, price) VALUES
('graduation', '本科', 12000, 'standard', 29.90),
('graduation', '硕士', 15000, 'academia', 49.90),
('journal', NULL, 5000, 'standard', 19.90);

INSERT INTO literature_refs (title, authors, source, pub_year, lang, gbt_citation, keywords) VALUES
('人工智能在教育领域的应用研究', '张三, 李四', '教育研究', 2023, 'zh',
 '张三, 李四. 人工智能在教育领域的应用研究[J]. 教育研究, 2023(5):12-20.', '人工智能,教育'),
('Deep Learning for NLP', 'Smith J', 'AI Review', 2022, 'en',
 'Smith J. Deep Learning for NLP[J]. AI Review, 2022, 15(3): 45-60.', 'NLP,deep learning');

INSERT INTO outline_templates (title, category, degree, depth, outline_json) VALUES
('教育经管类毕业论文提纲', '教育经管', '本科', 2,
 '[{"level":1,"title":"绪论","wordCount":800},{"level":1,"title":"理论基础","wordCount":1500},{"level":1,"title":"实证分析","wordCount":2000},{"level":1,"title":"结论与展望","wordCount":700}]'),
('计算机类毕业论文提纲', '计算机', '本科', 3,
 '[{"level":1,"title":"绪论","wordCount":600},{"level":2,"title":"研究背景","wordCount":400},{"level":1,"title":"系统设计","wordCount":1800}]');
